export const CHARACTERS = [
  { id: "gojo", name: "Satoru Gojo", anime: "JJK", universeRole: "mystic", powerLevel: 980, loyalty: 8, type: "Sorcerer", wikiTitle: "Satoru_Gojo" },
  { id: "sukuna", name: "Ryomen Sukuna", anime: "JJK", universeRole: "wildcard", powerLevel: 1000, loyalty: 2, type: "Curse King", wikiTitle: "Sukuna" },
  { id: "itadori", name: "Yuji Itadori", anime: "JJK", universeRole: "brawler", powerLevel: 840, loyalty: 9, type: "Vessel Fighter", wikiTitle: "Yuji_Itadori" },
  { id: "megumi", name: "Megumi Fushiguro", anime: "JJK", universeRole: "strategist", powerLevel: 780, loyalty: 8, type: "Shikigami User", wikiTitle: "Megumi_Fushiguro" },
  { id: "yuta", name: "Yuta Okkotsu", anime: "JJK", universeRole: "mystic", powerLevel: 910, loyalty: 9, type: "Special Grade", wikiTitle: "Yuta_Okkotsu" },
  { id: "nobara", name: "Nobara Kugisaki", anime: "JJK", universeRole: "assassin", powerLevel: 720, loyalty: 8, type: "Straw Doll User", wikiTitle: "Nobara_Kugisaki" },
  { id: "maki", name: "Maki Zenin", anime: "JJK", universeRole: "assassin", powerLevel: 850, loyalty: 8, type: "Weapon Specialist", wikiTitle: "Maki_Zenin" },
  { id: "toji", name: "Toji Fushiguro", anime: "JJK", universeRole: "assassin", powerLevel: 930, loyalty: 3, type: "Heavenly Restriction", wikiTitle: "Toji_Fushiguro" },
  { id: "geto", name: "Suguru Geto", anime: "JJK", universeRole: "leader", powerLevel: 900, loyalty: 3, type: "Curse Manipulator", wikiTitle: "Suguru_Geto" },
  { id: "nanami", name: "Kento Nanami", anime: "JJK", universeRole: "support", powerLevel: 790, loyalty: 10, type: "Grade 1 Sorcerer", wikiTitle: "Kento_Nanami" },

  { id: "yoriichi", name: "Yoriichi Tsugikuni", anime: "Demon Slayer", universeRole: "assassin", powerLevel: 960, loyalty: 9, type: "Sun Breather", wikiTitle: "Yoriichi_Tsugikuni" },
  { id: "muzan", name: "Muzan Kibutsuji", anime: "Demon Slayer", universeRole: "wildcard", powerLevel: 930, loyalty: 2, type: "Demon Lord", wikiTitle: "Muzan_Kibutsuji" },
  { id: "tanjiro", name: "Tanjiro Kamado", anime: "Demon Slayer", universeRole: "leader", powerLevel: 820, loyalty: 9, type: "Swordsman", wikiTitle: "Tanjiro_Kamado" },
  { id: "rengoku", name: "Kyojuro Rengoku", anime: "Demon Slayer", universeRole: "leader", powerLevel: 810, loyalty: 10, type: "Flame Hashira", wikiTitle: "Kyojuro_Rengoku" },
  { id: "inosuke", name: "Inosuke Hashibira", anime: "Demon Slayer", universeRole: "brawler", powerLevel: 760, loyalty: 8, type: "Beast Fighter", wikiTitle: "Inosuke_Hashibira" },
  { id: "zenitsu", name: "Zenitsu Agatsuma", anime: "Demon Slayer", universeRole: "assassin", powerLevel: 740, loyalty: 8, type: "Thunder Burst", wikiTitle: "Zenitsu_Agatsuma" },
  { id: "giyu", name: "Giyu Tomioka", anime: "Demon Slayer", universeRole: "support", powerLevel: 830, loyalty: 9, type: "Water Hashira", wikiTitle: "Giyu_Tomioka" },
  { id: "shinobu", name: "Shinobu Kocho", anime: "Demon Slayer", universeRole: "healer", powerLevel: 770, loyalty: 9, type: "Insect Hashira", wikiTitle: "Shinobu_Kocho" },
  { id: "akaza", name: "Akaza", anime: "Demon Slayer", universeRole: "brawler", powerLevel: 900, loyalty: 3, type: "Upper Moon", wikiTitle: "Akaza" },
  { id: "tengen", name: "Tengen Uzui", anime: "Demon Slayer", universeRole: "support", powerLevel: 790, loyalty: 8, type: "Sound Hashira", wikiTitle: "Tengen_Uzui" },

  { id: "eren", name: "Eren Yeager", anime: "AOT", universeRole: "wildcard", powerLevel: 920, loyalty: 4, type: "Founding Titan", wikiTitle: "Eren_Yeager" },
  { id: "levi", name: "Levi Ackerman", anime: "AOT", universeRole: "assassin", powerLevel: 800, loyalty: 9, type: "Elite Soldier", wikiTitle: "Levi_Ackerman" },
  { id: "mikasa", name: "Mikasa Ackerman", anime: "AOT", universeRole: "assassin", powerLevel: 780, loyalty: 8, type: "Ackerman", wikiTitle: "Mikasa_Ackerman" },
  { id: "armin", name: "Armin Arlert", anime: "AOT", universeRole: "strategist", powerLevel: 740, loyalty: 8, type: "Tactician", wikiTitle: "Armin_Arlert" },
  { id: "reiner", name: "Reiner Braun", anime: "AOT", universeRole: "tank", powerLevel: 830, loyalty: 5, type: "Armored Titan", wikiTitle: "Reiner_Braun" },
  { id: "erwin", name: "Erwin Smith", anime: "AOT", universeRole: "leader", powerLevel: 760, loyalty: 10, type: "Commander", wikiTitle: "Erwin_Smith" },
  { id: "annie", name: "Annie Leonhart", anime: "AOT", universeRole: "brawler", powerLevel: 810, loyalty: 5, type: "Female Titan", wikiTitle: "Annie_Leonhart" },
  { id: "zeke", name: "Zeke Yeager", anime: "AOT", universeRole: "ranged", powerLevel: 860, loyalty: 4, type: "Beast Titan", wikiTitle: "Zeke_Yeager" },
  { id: "hange", name: "Hange Zoe", anime: "AOT", universeRole: "support", powerLevel: 730, loyalty: 9, type: "Research Commander", wikiTitle: "Hange_Zoe" },
  { id: "jean", name: "Jean Kirstein", anime: "AOT", universeRole: "leader", powerLevel: 710, loyalty: 8, type: "Squad Leader", wikiTitle: "Jean_Kirstein" },

  { id: "ben10", name: "Ben Tennyson", anime: "Ben 10", universeRole: "wildcard", powerLevel: 940, loyalty: 8, type: "Omnitrix Hero", wikiTitle: "Ben_Tennyson" },
  { id: "kevin", name: "Kevin Levin", anime: "Ben 10", universeRole: "brawler", powerLevel: 820, loyalty: 6, type: "Absorber", wikiTitle: "Kevin_Levin" },
  { id: "gwen", name: "Gwen Tennyson", anime: "Ben 10", universeRole: "mystic", powerLevel: 780, loyalty: 8, type: "Anodite", wikiTitle: "Gwen_Tennyson" },
  { id: "vilgax", name: "Vilgax", anime: "Ben 10", universeRole: "tank", powerLevel: 900, loyalty: 3, type: "Conqueror", wikiTitle: "Vilgax" },
  { id: "max", name: "Max Tennyson", anime: "Ben 10", universeRole: "leader", powerLevel: 700, loyalty: 10, type: "Plumber", wikiTitle: "Max_Tennyson" },
  { id: "charmcaster", name: "Charmcaster", anime: "Ben 10", universeRole: "mystic", powerLevel: 790, loyalty: 4, type: "Magic User", wikiTitle: "Charmcaster" },
  { id: "albedo", name: "Albedo", anime: "Ben 10", universeRole: "strategist", powerLevel: 860, loyalty: 2, type: "Omnitrix Rival", wikiTitle: "Albedo_(Ben_10)" },
  { id: "rook", name: "Rook Blonko", anime: "Ben 10", universeRole: "support", powerLevel: 760, loyalty: 9, type: "Partner", wikiTitle: "Rook_Blonko" },
  { id: "aggregor", name: "Aggregor", anime: "Ben 10", universeRole: "wildcard", powerLevel: 870, loyalty: 2, type: "Absorption Warlord", wikiTitle: "Aggregor" },
  { id: "hex", name: "Hex", anime: "Ben 10", universeRole: "mystic", powerLevel: 740, loyalty: 4, type: "Sorcerer", wikiTitle: "Hex_(Ben_10)" },

  { id: "light", name: "Light Yagami", anime: "Death Note", universeRole: "strategist", powerLevel: 740, loyalty: 3, type: "Kira", wikiTitle: "Light_Yagami" },
  { id: "l", name: "L", anime: "Death Note", universeRole: "strategist", powerLevel: 720, loyalty: 8, type: "Detective", wikiTitle: "L_(Death_Note)" },
  { id: "ryuk", name: "Ryuk", anime: "Death Note", universeRole: "wildcard", powerLevel: 860, loyalty: 2, type: "Shinigami", wikiTitle: "Ryuk" },
  { id: "misa", name: "Misa Amane", anime: "Death Note", universeRole: "support", powerLevel: 630, loyalty: 5, type: "Kira Ally", wikiTitle: "Misa_Amane" },
  { id: "near", name: "Near", anime: "Death Note", universeRole: "strategist", powerLevel: 680, loyalty: 8, type: "Successor", wikiTitle: "Near_(Death_Note)" },
  { id: "mello", name: "Mello", anime: "Death Note", universeRole: "wildcard", powerLevel: 690, loyalty: 5, type: "Rival Genius", wikiTitle: "Mihael_Keehl" },
  { id: "rem", name: "Rem", anime: "Death Note", universeRole: "healer", powerLevel: 780, loyalty: 7, type: "Protective Shinigami", wikiTitle: "Rem_(Death_Note)" },
  { id: "soichiro", name: "Soichiro Yagami", anime: "Death Note", universeRole: "leader", powerLevel: 670, loyalty: 10, type: "Task Force Chief", wikiTitle: "Soichiro_Yagami" },
  { id: "matsuda", name: "Touta Matsuda", anime: "Death Note", universeRole: "support", powerLevel: 620, loyalty: 8, type: "Task Force Agent", wikiTitle: "Touta_Matsuda" },
  { id: "teru", name: "Teru Mikami", anime: "Death Note", universeRole: "assassin", powerLevel: 660, loyalty: 2, type: "Kira Disciple", wikiTitle: "Teru_Mikami" },

  { id: "saitama", name: "Saitama", anime: "OPM", universeRole: "brawler", powerLevel: 1100, loyalty: 7, type: "Hero", wikiTitle: "Saitama" },
  { id: "garou", name: "Garou", anime: "OPM", universeRole: "brawler", powerLevel: 930, loyalty: 5, type: "Martial Monster", wikiTitle: "Garou" },
  { id: "tatsumaki", name: "Tatsumaki", anime: "OPM", universeRole: "mystic", powerLevel: 900, loyalty: 6, type: "Esper", wikiTitle: "Tatsumaki" },
  { id: "genos", name: "Genos", anime: "OPM", universeRole: "assassin", powerLevel: 820, loyalty: 8, type: "Cyborg", wikiTitle: "Genos_(One-Punch_Man)" },
  { id: "bang", name: "Silver Fang", anime: "OPM", universeRole: "leader", powerLevel: 850, loyalty: 9, type: "Master", wikiTitle: "Bang_(One-Punch_Man)" },
  { id: "boros", name: "Boros", anime: "OPM", universeRole: "tank", powerLevel: 980, loyalty: 3, type: "Cosmic Invader", wikiTitle: "Boros_(One-Punch_Man)" },
  { id: "king", name: "King", anime: "OPM", universeRole: "wildcard", powerLevel: 700, loyalty: 9, type: "Luck Hero", wikiTitle: "King_(One-Punch_Man)" },
  { id: "fubuki", name: "Fubuki", anime: "OPM", universeRole: "support", powerLevel: 760, loyalty: 8, type: "Esper Support", wikiTitle: "Fubuki" },
  { id: "atomic", name: "Atomic Samurai", anime: "OPM", universeRole: "assassin", powerLevel: 860, loyalty: 8, type: "Sword Master", wikiTitle: "Atomic_Samurai" },
  { id: "speedo", name: "Speed-o'-Sound Sonic", anime: "OPM", universeRole: "assassin", powerLevel: 830, loyalty: 4, type: "Ninja", wikiTitle: "Speed-o%27-Sound_Sonic" },

  { id: "ironman", name: "Iron Man", anime: "Marvel", universeRole: "strategist", powerLevel: 900, loyalty: 8, type: "Tech Avenger", wikiTitle: "Iron_Man" },
  { id: "captainamerica", name: "Captain America", anime: "Marvel", universeRole: "leader", powerLevel: 840, loyalty: 10, type: "Super Soldier", wikiTitle: "Captain_America" },
  { id: "thor", name: "Thor", anime: "Marvel", universeRole: "tank", powerLevel: 980, loyalty: 8, type: "Asgardian", wikiTitle: "Thor" },
  { id: "hulk", name: "Hulk", anime: "Marvel", universeRole: "brawler", powerLevel: 1000, loyalty: 6, type: "Gamma Titan", wikiTitle: "Hulk" },
  { id: "blackwidow", name: "Black Widow", anime: "Marvel", universeRole: "assassin", powerLevel: 760, loyalty: 8, type: "Spy", wikiTitle: "Black_Widow_(Natasha_Romanova)" },
  { id: "spiderman", name: "Spider-Man", anime: "Marvel", universeRole: "assassin", powerLevel: 860, loyalty: 9, type: "Web Hero", wikiTitle: "Spider-Man" },
  { id: "doctorstrange", name: "Doctor Strange", anime: "Marvel", universeRole: "mystic", powerLevel: 960, loyalty: 7, type: "Sorcerer Supreme", wikiTitle: "Doctor_Strange" },
  { id: "scarletwitch", name: "Scarlet Witch", anime: "Marvel", universeRole: "mystic", powerLevel: 970, loyalty: 5, type: "Chaos Witch", wikiTitle: "Scarlet_Witch" },
  { id: "thanos", name: "Thanos", anime: "Marvel", universeRole: "wildcard", powerLevel: 1020, loyalty: 2, type: "Titan Warlord", wikiTitle: "Thanos" },
  { id: "loki", name: "Loki", anime: "Marvel", universeRole: "wildcard", powerLevel: 880, loyalty: 3, type: "Trickster", wikiTitle: "Loki" },

  { id: "superman", name: "Superman", anime: "DC", universeRole: "tank", powerLevel: 1020, loyalty: 9, type: "Kryptonian", wikiTitle: "Superman" },
  { id: "batman", name: "Batman", anime: "DC", universeRole: "strategist", powerLevel: 860, loyalty: 8, type: "Dark Knight", wikiTitle: "Batman" },
  { id: "wonderwoman", name: "Wonder Woman", anime: "DC", universeRole: "leader", powerLevel: 940, loyalty: 9, type: "Amazon Warrior", wikiTitle: "Wonder_Woman" },
  { id: "flash", name: "The Flash", anime: "DC", universeRole: "ranged", powerLevel: 930, loyalty: 8, type: "Speedster", wikiTitle: "Flash_(DC_Comics_character)" },
  { id: "aquaman", name: "Aquaman", anime: "DC", universeRole: "tank", powerLevel: 860, loyalty: 8, type: "Atlantean King", wikiTitle: "Aquaman" },
  { id: "cyborg", name: "Cyborg", anime: "DC", universeRole: "support", powerLevel: 840, loyalty: 8, type: "Tech Hero", wikiTitle: "Cyborg_(DC_Comics)" },
  { id: "greenlantern", name: "Green Lantern", anime: "DC", universeRole: "mystic", powerLevel: 900, loyalty: 8, type: "Ring Bearer", wikiTitle: "Green_Lantern" },
  { id: "darkseid", name: "Darkseid", anime: "DC", universeRole: "wildcard", powerLevel: 1010, loyalty: 2, type: "Apokolips Lord", wikiTitle: "Darkseid" },
  { id: "joker", name: "Joker", anime: "DC", universeRole: "wildcard", powerLevel: 780, loyalty: 1, type: "Chaos Master", wikiTitle: "Joker_(character)" },
  { id: "shazam", name: "Shazam", anime: "DC", universeRole: "brawler", powerLevel: 920, loyalty: 8, type: "Magic Champion", wikiTitle: "Captain_Marvel_(DC_Comics)" },

  // Booster/Action Cards (40 total)
  { id: "boost-uturn-1", name: "U-Turn", anime: "Arcade", universeRole: "wildcard", powerLevel: 50, loyalty: 5, type: "Booster", effect: "reverse_turn", description: "Skip opponent's next draft turn." },
  { id: "boost-uturn-2", name: "U-Turn", anime: "Arcade", universeRole: "wildcard", powerLevel: 50, loyalty: 5, type: "Booster", effect: "reverse_turn", description: "Skip opponent's next draft turn." },
  { id: "boost-uturn-3", name: "U-Turn", anime: "Arcade", universeRole: "wildcard", powerLevel: 50, loyalty: 5, type: "Booster", effect: "reverse_turn", description: "Skip opponent's next draft turn." },
  { id: "boost-uturn-4", name: "U-Turn", anime: "Arcade", universeRole: "wildcard", powerLevel: 50, loyalty: 5, type: "Booster", effect: "reverse_turn", description: "Skip opponent's next draft turn." },

  { id: "boost-draw2-1", name: "Draw 2", anime: "Arcade", universeRole: "strategist", powerLevel: 45, loyalty: 6, type: "Booster", effect: "draw_two_cards", description: "Draw up to 2 extra cards for team drafting." },
  { id: "boost-draw2-2", name: "Draw 2", anime: "Arcade", universeRole: "strategist", powerLevel: 45, loyalty: 6, type: "Booster", effect: "draw_two_cards", description: "Draw up to 2 extra cards for team drafting." },
  { id: "boost-draw2-3", name: "Draw 2", anime: "Arcade", universeRole: "strategist", powerLevel: 45, loyalty: 6, type: "Booster", effect: "draw_two_cards", description: "Draw up to 2 extra cards for team drafting." },
  { id: "boost-draw2-4", name: "Draw 2", anime: "Arcade", universeRole: "strategist", powerLevel: 45, loyalty: 6, type: "Booster", effect: "draw_two_cards", description: "Draw up to 2 extra cards for team drafting." },

  { id: "boost-swap-1", name: "Swap Card", anime: "Arcade", universeRole: "support", powerLevel: 40, loyalty: 7, type: "Booster", effect: "swap_one_card", description: "Swap one assigned role card with a hand card." },
  { id: "boost-swap-2", name: "Swap Card", anime: "Arcade", universeRole: "support", powerLevel: 40, loyalty: 7, type: "Booster", effect: "swap_one_card", description: "Swap one assigned role card with a hand card." },
  { id: "boost-swap-3", name: "Swap Card", anime: "Arcade", universeRole: "support", powerLevel: 40, loyalty: 7, type: "Booster", effect: "swap_one_card", description: "Swap one assigned role card with a hand card." },
  { id: "boost-swap-4", name: "Swap Card", anime: "Arcade", universeRole: "support", powerLevel: 40, loyalty: 7, type: "Booster", effect: "swap_one_card", description: "Swap one assigned role card with a hand card." },

  { id: "boost-shield-1", name: "Shield", anime: "Arcade", universeRole: "healer", powerLevel: 35, loyalty: 8, type: "Booster", effect: "shield_team", description: "Reduce opponent team power by 10% in battle." },
  { id: "boost-shield-2", name: "Shield", anime: "Arcade", universeRole: "healer", powerLevel: 35, loyalty: 8, type: "Booster", effect: "shield_team", description: "Reduce opponent team power by 10% in battle." },
  { id: "boost-shield-3", name: "Shield", anime: "Arcade", universeRole: "healer", powerLevel: 35, loyalty: 8, type: "Booster", effect: "shield_team", description: "Reduce opponent team power by 10% in battle." },
  { id: "boost-shield-4", name: "Shield", anime: "Arcade", universeRole: "healer", powerLevel: 35, loyalty: 8, type: "Booster", effect: "shield_team", description: "Reduce opponent team power by 10% in battle." },

  { id: "boost-boost-1", name: "Power Boost", anime: "Arcade", universeRole: "brawler", powerLevel: 55, loyalty: 5, type: "Booster", effect: "power_boost", description: "Increase team attack power by 30% in battle." },
  { id: "boost-boost-2", name: "Power Boost", anime: "Arcade", universeRole: "brawler", powerLevel: 55, loyalty: 5, type: "Booster", effect: "power_boost", description: "Increase team attack power by 30% in battle." },
  { id: "boost-boost-3", name: "Power Boost", anime: "Arcade", universeRole: "brawler", powerLevel: 55, loyalty: 5, type: "Booster", effect: "power_boost", description: "Increase team attack power by 30% in battle." },
  { id: "boost-boost-4", name: "Power Boost", anime: "Arcade", universeRole: "brawler", powerLevel: 55, loyalty: 5, type: "Booster", effect: "power_boost", description: "Increase team attack power by 30% in battle." },

  { id: "boost-steal-1", name: "Steal Card", anime: "Arcade", universeRole: "assassin", powerLevel: 38, loyalty: 3, type: "Booster", effect: "steal_card", description: "Randomly steal 1 card from opponent hand." },
  { id: "boost-steal-2", name: "Steal Card", anime: "Arcade", universeRole: "assassin", powerLevel: 38, loyalty: 3, type: "Booster", effect: "steal_card", description: "Randomly steal 1 card from opponent hand." },
  { id: "boost-steal-3", name: "Steal Card", anime: "Arcade", universeRole: "assassin", powerLevel: 38, loyalty: 3, type: "Booster", effect: "steal_card", description: "Randomly steal 1 card from opponent hand." },
  { id: "boost-steal-4", name: "Steal Card", anime: "Arcade", universeRole: "assassin", powerLevel: 38, loyalty: 3, type: "Booster", effect: "steal_card", description: "Randomly steal 1 card from opponent hand." },

  { id: "boost-heal-1", name: "Heal Up", anime: "Arcade", universeRole: "healer", powerLevel: 42, loyalty: 8, type: "Booster", effect: "heal_team", description: "Increase team sustain by 25% in battle." },
  { id: "boost-heal-2", name: "Heal Up", anime: "Arcade", universeRole: "healer", powerLevel: 42, loyalty: 8, type: "Booster", effect: "heal_team", description: "Increase team sustain by 25% in battle." },
  { id: "boost-heal-3", name: "Heal Up", anime: "Arcade", universeRole: "healer", powerLevel: 42, loyalty: 8, type: "Booster", effect: "heal_team", description: "Increase team sustain by 25% in battle." },
  { id: "boost-heal-4", name: "Heal Up", anime: "Arcade", universeRole: "healer", powerLevel: 42, loyalty: 8, type: "Booster", effect: "heal_team", description: "Increase team sustain by 25% in battle." },

  { id: "boost-double-1", name: "Double Strike", anime: "Arcade", universeRole: "brawler", powerLevel: 48, loyalty: 5, type: "Booster", effect: "double_damage", description: "Increase team attack by 10% in battle." },
  { id: "boost-double-2", name: "Double Strike", anime: "Arcade", universeRole: "brawler", powerLevel: 48, loyalty: 5, type: "Booster", effect: "double_damage", description: "Increase team attack by 10% in battle." },
  { id: "boost-double-3", name: "Double Strike", anime: "Arcade", universeRole: "brawler", powerLevel: 48, loyalty: 5, type: "Booster", effect: "double_damage", description: "Increase team attack by 10% in battle." },
  { id: "boost-double-4", name: "Double Strike", anime: "Arcade", universeRole: "brawler", powerLevel: 48, loyalty: 5, type: "Booster", effect: "double_damage", description: "Increase team attack by 10% in battle." },

  { id: "boost-lock-1", name: "Lock In", anime: "Arcade", universeRole: "strategist", powerLevel: 36, loyalty: 7, type: "Booster", effect: "lock_hand", description: "Lock opponent draw and booster slot next turn." },
  { id: "boost-lock-2", name: "Lock In", anime: "Arcade", universeRole: "strategist", powerLevel: 36, loyalty: 7, type: "Booster", effect: "lock_hand", description: "Lock opponent draw and booster slot next turn." },
  { id: "boost-lock-3", name: "Lock In", anime: "Arcade", universeRole: "strategist", powerLevel: 36, loyalty: 7, type: "Booster", effect: "lock_hand", description: "Lock opponent draw and booster slot next turn." },
  { id: "boost-lock-4", name: "Lock In", anime: "Arcade", universeRole: "strategist", powerLevel: 36, loyalty: 7, type: "Booster", effect: "lock_hand", description: "Lock opponent draw and booster slot next turn." },

  { id: "boost-reload-1", name: "Reload", anime: "Arcade", universeRole: "leader", powerLevel: 44, loyalty: 6, type: "Booster", effect: "reload_deck", description: "Reshuffle your discard pile into draft deck." },
  { id: "boost-reload-2", name: "Reload", anime: "Arcade", universeRole: "leader", powerLevel: 44, loyalty: 6, type: "Booster", effect: "reload_deck", description: "Reshuffle your discard pile into draft deck." }
];

export const ROLES = ["captain", "viceCaptain", "healer", "support", "traitor"];
